# Generated by Django 2.1.5 on 2019-03-31 23:00

import uuid

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_column="uuid", default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("deleted", "Deleted"), ("created", "Created"), ("approved", "Approved")],
                        default="created",
                        max_length=32,
                        verbose_name="Status",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True, verbose_name="Created date")),
                ("updated_date", models.DateTimeField(auto_now=True, verbose_name="Updated date")),
                ("object_id", models.UUIDField(blank=True, null=True, verbose_name="Object UUID")),
                ("address", models.TextField(verbose_name="Address")),
                ("latitude", models.FloatField(blank=True, null=True, verbose_name="Latitude")),
                ("longitude", models.FloatField(blank=True, null=True, verbose_name="Longitude")),
                ("name", models.CharField(max_length=255, unique=True, verbose_name="Name")),
                ("description", ckeditor.fields.RichTextField(blank=True, null=True, verbose_name="Description")),
                ("start_date", models.DateTimeField(verbose_name="Start date")),
                ("end_date", models.DateTimeField(verbose_name="End date")),
                ("man_cost", models.FloatField(default=0, verbose_name="Man cost")),
                ("woman_cost", models.FloatField(default=0, verbose_name="Woman cost")),
                ("pair_cost", models.FloatField(default=0, verbose_name="Pair cost")),
            ],
            options={"verbose_name": "event", "verbose_name_plural": "events"},
        )
    ]
