# Generated by Django 2.1.5 on 2019-03-31 23:00

import apps.events.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def limit_choices_to_content_type():
    return ()


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("events", "0001_initial"),
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("storage", "0002_auto_20190331_2300"),
        ("geo", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="administrator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name="Administrator"
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="avatar",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="storage.Image",
                verbose_name="Avatar",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="city",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="geo.City", verbose_name="City"
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="content_type",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to=limit_choices_to_content_type,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.ContentType",
                verbose_name="Content type",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="country",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="geo.Country", verbose_name="Country"
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="moderators",
            field=models.ManyToManyField(
                blank=True, related_name="moderator_events", to=settings.AUTH_USER_MODEL, verbose_name="Moderators"
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="region",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="geo.Region", verbose_name="Region"
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="users",
            field=models.ManyToManyField(
                blank=True, related_name="user_events", to=settings.AUTH_USER_MODEL, verbose_name="Users"
            ),
        ),
    ]
