# Generated by Django 2.1.5 on 2019-04-13 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("events", "0002_auto_20190331_2300")]

    operations = [
        migrations.AlterModelOptions(name="event", options={"verbose_name": "Event", "verbose_name_plural": "Events"})
    ]
