# Generated by Django 2.1.5 on 2019-04-17 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("events", "0005_auto_20190416_1027")]

    operations = [
        migrations.RemoveField(model_name="event", name="status"),
        migrations.AddField(
            model_name="event",
            name="is_deleted",
            field=models.BooleanField(db_index=True, default=False, verbose_name="Is deleted"),
        ),
    ]
