# Generated by Django 2.1.5 on 2019-05-01 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("events", "0006_auto_20190417_0627")]

    operations = [
        migrations.RemoveField(model_name="event", name="country"),
        migrations.RemoveField(model_name="event", name="region"),
    ]
