# Generated by Django 2.1.5 on 2019-05-05 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("events", "0007_auto_20190501_1939")]

    operations = []
