# Generated by Django 2.1.5 on 2019-05-05 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("events", "0008_auto_20190505_0843")]

    operations = []
