# Generated by Django 2.1.5 on 2019-09-04 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("events", "0009_event_city")]

    operations = [migrations.RemoveField(model_name="event", name="city")]
