# Generated by Django 2.1.5 on 2019-09-04 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("cities_light", "0008_city_timezone"), ("events", "0010_remove_event_city")]

    operations = [
        migrations.AddField(
            model_name="event",
            name="city",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="cities_light.City", verbose_name="City"
            ),
        )
    ]
