# Generated by Django 2.1.5 on 2019-10-10 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("events", "0013_party_party_type")]

    operations = [
        migrations.AlterField(
            model_name="partyuser",
            name="status",
            field=models.CharField(
                choices=[("no", "No"), ("yes", "Yes"), ("probably", "Probably")], max_length=16, verbose_name="Theme"
            ),
        )
    ]
