# Generated by Django 2.1.5 on 2020-02-16 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("clubs", "0037_auto_20191010_1625"), ("events", "0014_auto_20191010_1338")]

    operations = [
        migrations.RemoveField(model_name="party", name="creator"),
        migrations.RemoveField(model_name="party", name="moderators"),
        migrations.RemoveField(model_name="party", name="users"),
        migrations.AddField(
            model_name="party",
            name="club",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="clubs.Club", verbose_name="Club"
            ),
        ),
    ]
