# Generated by Django 2.1.5 on 2020-02-16 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("events", "00017_club")]

    operations = [
        migrations.RemoveField(model_name="party", name="content_type"),
        migrations.RemoveField(model_name="party", name="object_id"),
        migrations.AlterField(
            model_name="party", name="name", field=models.CharField(max_length=255, verbose_name="Name")
        ),
    ]
