# Generated by Django 2.1.5 on 2020-02-16 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("events", "0019_auto_20200216_0757")]

    operations = [
        migrations.AddField(
            model_name="party",
            name="is_ban",
            field=models.BooleanField(db_index=True, default=False, verbose_name="Is ban"),
        ),
        migrations.AddField(
            model_name="party",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[("waiting", "Waiting moderation"), ("approved", "Approved"), ("declined", "Declined")],
                db_index=True,
                max_length=32,
                null=True,
                verbose_name="Status",
            ),
        ),
    ]
