# Generated by Django 2.1.5 on 2019-05-17 18:38

import uuid

import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL)]

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_column="uuid", default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True, verbose_name="Created date")),
                ("updated_date", models.DateTimeField(auto_now=True, verbose_name="Updated date")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, verbose_name="Is deleted")),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                ("description", ckeditor.fields.RichTextField(verbose_name="Description")),
                ("hash_tags", models.TextField(blank=True, null=True, verbose_name="Hash tags")),
                ("views", models.PositiveIntegerField(default=0, verbose_name="Views")),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name="Creator"
                    ),
                ),
                (
                    "likes",
                    models.ManyToManyField(
                        blank=True, related_name="like_games", to=settings.AUTH_USER_MODEL, verbose_name="Likes"
                    ),
                ),
            ],
            options={"verbose_name": "Game", "verbose_name_plural": "Games"},
        )
    ]
