# Generated by Django 2.1.5 on 2019-05-17 19:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL), ("games", "0002_auto_20190517_1854")]

    operations = [
        migrations.AddField(
            model_name="gameuser", name="expired", field=models.DateField(blank=True, null=True, verbose_name="Expired")
        ),
        migrations.AlterUniqueTogether(name="gameuser", unique_together={("user", "game")}),
    ]
