# Generated by Django 2.1.5 on 2019-05-17 20:23

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("games", "0003_auto_20190517_1909")]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="hash_tags",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=255), default=list, size=None, verbose_name="Hash tags"
            ),
        )
    ]
