# Generated by Django 2.1.5 on 2019-05-18 09:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("games", "0004_auto_20190517_2023")]

    operations = [
        migrations.AlterField(
            model_name="gameuser",
            name="game",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="game_gameusers",
                to="games.Game",
                verbose_name="Game",
            ),
        ),
        migrations.AlterField(
            model_name="gameuser",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_gameusers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
    ]
