# Generated by Django 2.1.5 on 2019-05-18 15:15

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("games", "0005_auto_20190518_0949")]

    operations = [
        migrations.AddField(
            model_name="game",
            name="rules",
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name="Rules"),
        )
    ]
