# Generated by Django 2.1.5 on 2019-05-19 10:05

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("games", "0008_game_slug")]

    operations = [
        migrations.AlterField(
            model_name="gameuser",
            name="game_data",
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, verbose_name="Game data"),
        )
    ]
