# Generated by Django 2.1.5 on 2019-10-07 12:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL), ("games", "0009_auto_20190519_1005")]

    operations = [
        migrations.AddField(
            model_name="game",
            name="users",
            field=models.ManyToManyField(
                blank=True,
                related_name="user_games",
                through="games.GameUser",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Users",
            ),
        )
    ]
