default_language_version:
  python: python3.7
fail_fast: true
repos:
  - repo: https://github.com/Yelp/detect-secrets
    rev: v0.12.7
    hooks:
      - id: detect-secrets
        args: ['--baseline', '.secrets.baseline']
        exclude: .*/tests/.*

  - repo: https://github.com/asottile/seed-isort-config
    rev: v1.2.0
    hooks:
    - id: seed-isort-config
      args: [--application-directories=apps]

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.20
    hooks:
    - id: isort

  - repo: https://github.com/psf/black
    rev: 19.3b0
    hooks:
      - id: black
        additional_dependencies: [toml]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.2.3
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-merge-conflict
      - id: flake8
      - id: detect-private-key
