version: "2.1"

volumes:
  postgres_data: {}
  media_data: {}
  static_data: {}

services:
  postgres:
    image: postgres:10.5-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./envsets/env.prod
    ports:
      - "5432:5432"
    healthcheck:
      test: "PGPASSWORD=postgrespass psql --host 127.0.0.1 --dbname postgresuser --username postgresuser --quiet --no-align --tuples-only -c 'SELECT 1;'"
      interval: 30s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3.7.14-alpine
    ports:
      - "5672:5672"
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      timeout: 5s
      interval: 5s
      retries: 5

  django-base: &django-base
    build:
      context: .
      dockerfile: ./compose/Dockerfile
    env_file:
      - ./envsets/env.prod
    volumes:
      - .:/app/server
      - media_data:/app/server/config/server_media
      - static_data:/app/server/config/server_static
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  celeryworker:
    <<: *django-base
    command: celery -A config worker -l INFO --purge

  celerybeat:
    <<: *django-base
    command: celery -A config beat -l INFO

  django:
    <<: *django-base
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      celeryworker:
        condition: service_started
      celerybeat:
        condition: service_started
    ports:
      - "8000:8000"
    command: ./compose/start.sh
