[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
line_length = 120
skip_glob = '**/migrations/*.py'
not_skip = '__init__.py'
known_first_party = 'apps'

[tool.black]
line-length = 120
exclude = '.git|migrations|static|staticfiles'
