# Generated by Django 2.1.5 on 2019-08-13 19:25

import uuid

import apps.news.models
import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("contenttypes", "0002_remove_content_type_name"),
        ("storage", "0003_auto_20190417_0627"),
    ]

    operations = [
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_column="uuid", default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True, verbose_name="Created date")),
                ("updated_date", models.DateTimeField(auto_now=True, verbose_name="Updated date")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, verbose_name="Is deleted")),
                ("object_id", models.UUIDField(blank=True, null=True, verbose_name="Object UUID")),
                ("title", models.CharField(blank=True, max_length=255, null=True, verbose_name="Title")),
                ("description", ckeditor.fields.RichTextField(blank=True, null=True, verbose_name="Description")),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to=apps.news.models.limit_choices_to_content_type,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.ContentType",
                        verbose_name="Content type",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name="Creator"
                    ),
                ),
                (
                    "image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="storage.Image",
                        verbose_name="Image",
                    ),
                ),
            ],
            options={"verbose_name": "News", "verbose_name_plural": "News"},
        )
    ]
