# Generated by Django 2.1.5 on 2019-08-13 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("news", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="news",
            name="news_type",
            field=models.CharField(
                choices=[("new_friend_image", "New friend image")],
                default="new_friend_image",
                max_length=16,
                verbose_name="Type",
            ),
            preserve_default=False,
        )
    ]
