# Generated by Django 2.1.5 on 2019-08-20 09:20

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("news", "0002_news_news_type")]

    operations = [
        migrations.AddField(
            model_name="news",
            name="date_published",
            field=models.DateField(blank=True, null=True, verbose_name="Date Published"),
        ),
        migrations.AddField(
            model_name="news",
            name="news",
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name="News"),
        ),
        migrations.AlterField(
            model_name="news",
            name="news_type",
            field=models.CharField(
                choices=[("site_news", "Site news"), ("new_friend_image", "New friend image")],
                max_length=16,
                verbose_name="Type",
            ),
        ),
    ]
