# Generated by Django 2.1.5 on 2019-08-20 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("news", "0003_auto_20190820_0920")]

    operations = [
        migrations.RemoveField(model_name="news", name="date_published"),
        migrations.AddField(
            model_name="news",
            name="publish_date",
            field=models.DateField(blank=True, null=True, verbose_name="Publish Date"),
        ),
    ]
