# Generated by Django 2.1.5 on 2019-08-20 09:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL), ("news", "0004_auto_20190820_0921")]

    operations = [
        migrations.AddField(
            model_name="news",
            name="recipients",
            field=models.ManyToManyField(
                blank=True, related_name="recipient_news", to=settings.AUTH_USER_MODEL, verbose_name="Recipients"
            ),
        ),
        migrations.AlterField(
            model_name="news",
            name="creator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creator",
            ),
        ),
    ]
