# Generated by Django 2.1.5 on 2019-08-20 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("news", "0006_news_viewed_by")]

    operations = [migrations.RemoveField(model_name="news", name="news")]
