# Generated by Django 2.1.5 on 2019-09-09 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("news", "0007_remove_news_news")]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="news_type",
            field=models.CharField(
                choices=[
                    ("site_news", "Site news"),
                    ("articles", "Articles"),
                    ("new_friend_image", "New friend image"),
                ],
                max_length=16,
                verbose_name="Type",
            ),
        )
    ]
