# Generated by Django 2.1.5 on 2019-09-09 23:27

import django.contrib.postgres.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL), ("news", "0008_auto_20190909_2242")]

    operations = [
        migrations.AddField(
            model_name="news",
            name="hash_tags",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=255), default=list, size=None, verbose_name="Hash tags"
            ),
        ),
        migrations.AddField(
            model_name="news",
            name="likes",
            field=models.ManyToManyField(
                blank=True, related_name="like_news", to=settings.AUTH_USER_MODEL, verbose_name="Likes"
            ),
        ),
        migrations.AddField(
            model_name="news", name="views", field=models.PositiveIntegerField(default=0, verbose_name="Views")
        ),
    ]
