# Generated by Django 2.1.5 on 2019-09-24 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("news", "0013_auto_20190922_1213")]

    operations = [
        migrations.AddField(
            model_name="news",
            name="end_publish_date",
            field=models.DateTimeField(blank=True, null=True, verbose_name="End Publish Date"),
        ),
        migrations.AlterField(
            model_name="news",
            name="publish_date",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Publish Date"),
        ),
    ]
