# Generated by Django 2.1.5 on 2019-09-25 10:00

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("news", "0015_auto_20190925_0940")]

    operations = [
        migrations.AddField(
            model_name="news",
            name="news",
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name="Post"),
        )
    ]
