# Generated by Django 2.2.10 on 2020-02-20 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("news", "0016_news_news")]

    operations = [
        migrations.AddField(
            model_name="news",
            name="theme",
            field=models.CharField(
                blank=True,
                choices=[
                    ("swing", "Swing"),
                    ("bdsm", "Bdsm"),
                    ("virt", "Virt"),
                    ("lgbt", "LGBT"),
                    ("poliamoria", "Poliamoria"),
                    ("other", "Other"),
                ],
                max_length=64,
                null=True,
                verbose_name="Theme",
            ),
        )
    ]
