# Generated by Django 2.2.10 on 2020-03-23 10:32

import uuid

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MobileVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_column="uuid", default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True, verbose_name="Created date")),
                ("updated_date", models.DateTimeField(auto_now=True, verbose_name="Updated date")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, verbose_name="Is deleted")),
                ("version", models.CharField(max_length=255, verbose_name="Version")),
                ("android_apk", models.FileField(blank=True, null=True, upload_to="", verbose_name="Android APK")),
                ("readme", ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name="Readme")),
            ],
            options={
                "verbose_name": "Mobile Version",
                "verbose_name_plural": "Mobile Versions",
                "ordering": ["-created_date"],
            },
        )
    ]
