# Generated by Django 2.1.5 on 2019-03-31 23:00

import uuid

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_column="uuid", default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("deleted", "Deleted"), ("created", "Created"), ("approved", "Approved")],
                        default="created",
                        max_length=32,
                        verbose_name="Status",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True, verbose_name="Created date")),
                ("updated_date", models.DateTimeField(auto_now=True, verbose_name="Updated date")),
                ("name", models.CharField(max_length=255, unique=True, verbose_name="Name")),
                (
                    "relationship_theme",
                    models.CharField(
                        choices=[
                            ("swing", "Swing"),
                            ("swing_history", "Swing History"),
                            ("bdsm", "Bdsm"),
                            ("bdsm_history", "Bdsm History"),
                            ("rule", "Rule"),
                            ("rule_media", "Rule Media"),
                            ("advertisment", "Advertisment"),
                        ],
                        max_length=16,
                        verbose_name="Relationship themes",
                    ),
                ),
                ("raiting", models.PositiveIntegerField(default=0, verbose_name="Raiting")),
                (
                    "group_type",
                    models.CharField(
                        choices=[("open", "Open"), ("close", "Close")], max_length=16, verbose_name="Type"
                    ),
                ),
                ("description", ckeditor.fields.RichTextField(blank=True, null=True, verbose_name="Description")),
            ],
            options={"verbose_name": "group", "verbose_name_plural": "groups"},
        )
    ]
