# Generated by Django 2.1.5 on 2019-04-16 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("groups", "0004_auto_20190413_0524")]

    operations = [migrations.RenameField(model_name="group", old_name="administrator", new_name="creator")]
