# Generated by Django 2.1.5 on 2019-04-23 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("groups", "0007_auto_20190417_0627")]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="group_type",
            field=models.CharField(
                choices=[("open", "Open"), ("close", "Close")], db_index=True, max_length=16, verbose_name="Type"
            ),
        ),
        migrations.AlterField(
            model_name="group",
            name="name",
            field=models.CharField(db_index=True, max_length=255, unique=True, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="group",
            name="relationship_theme",
            field=models.CharField(
                choices=[("swing", "Swing"), ("bdsm", "Bdsm"), ("virt", "Virt"), ("other", "Other")],
                db_index=True,
                max_length=16,
                verbose_name="Relationship themes",
            ),
        ),
    ]
