# Generated by Django 2.1.5 on 2019-05-13 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("groups", "0016_auto_20190507_0848")]

    operations = [
        migrations.AlterUniqueTogether(name="grouprequest", unique_together=set()),
        migrations.RemoveField(model_name="grouprequest", name="group"),
        migrations.RemoveField(model_name="grouprequest", name="user"),
        migrations.DeleteModel(name="GroupRequest"),
    ]
