# Generated by Django 2.1.5 on 2020-02-16 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("groups", "0019_auto_20190516_2224")]

    operations = [migrations.RenameField(model_name="group", old_name="avatar", new_name="image")]
