# Generated by Django 2.1.5 on 2020-02-16 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("groups", "00022_group_slug")]

    operations = [
        migrations.AlterField(
            model_name="group", name="slug", field=models.SlugField(max_length=150, unique=True, verbose_name="Slug")
        )
    ]
