# Generated by Django 2.1.5 on 2019-03-31 23:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [("shops", "0001_initial"), ("storage", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="shopitem",
            name="image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="storage.Image",
                verbose_name="Image",
            ),
        ),
        migrations.AddField(
            model_name="shopitem",
            name="shop",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="shops.Shop", verbose_name="Shop"),
        ),
    ]
