# Generated by Django 2.1.5 on 2019-04-13 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("shops", "0003_auto_20190331_2300")]

    operations = [
        migrations.AlterModelOptions(name="shop", options={"verbose_name": "Shop", "verbose_name_plural": "Shops"}),
        migrations.AlterModelOptions(name="shopitem", options={"verbose_name": "Item", "verbose_name_plural": "Items"}),
    ]
