# Generated by Django 2.1.5 on 2019-04-17 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("shops", "0006_auto_20190416_1044")]

    operations = [
        migrations.RemoveField(model_name="shop", name="status"),
        migrations.RemoveField(model_name="shopitem", name="status"),
        migrations.AddField(
            model_name="shop",
            name="is_deleted",
            field=models.BooleanField(db_index=True, default=False, verbose_name="Is deleted"),
        ),
        migrations.AddField(
            model_name="shopitem",
            name="is_deleted",
            field=models.BooleanField(db_index=True, default=False, verbose_name="Is deleted"),
        ),
    ]
