# Generated by Django 2.1.5 on 2019-04-13 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("clubs", "0003_auto_20190409_1029")]

    operations = [
        migrations.AlterModelOptions(name="club", options={"verbose_name": "Club", "verbose_name_plural": "Clubs"})
    ]
