# Generated by Django 2.1.5 on 2019-04-22 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("clubs", "0007_auto_20190417_0627")]

    operations = [
        migrations.AlterField(
            model_name="club", name="name", field=models.CharField(db_index=True, max_length=255, verbose_name="Name")
        )
    ]
