# Generated by Django 2.1.5 on 2019-04-23 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("clubs", "0009_auto_20190422_2041")]

    operations = [
        migrations.AlterField(
            model_name="club",
            name="club_type",
            field=models.CharField(
                choices=[("open", "Open"), ("close", "Close")], db_index=True, max_length=16, verbose_name="Type"
            ),
        ),
        migrations.AlterField(
            model_name="club",
            name="relationship_theme",
            field=models.CharField(
                choices=[("swing", "Swing"), ("bdsm", "Bdsm"), ("virt", "Virt"), ("other", "Other")],
                db_index=True,
                max_length=16,
                verbose_name="Relationship themes",
            ),
        ),
    ]
