# Generated by Django 2.1.5 on 2019-04-28 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("clubs", "0012_auto_20190427_2008")]

    operations = [
        migrations.AlterModelOptions(
            name="clubrequest", options={"verbose_name": "Club request", "verbose_name_plural": "Club requests"}
        )
    ]
