# Generated by Django 2.1.5 on 2019-04-28 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("clubs", "0013_auto_20190428_0651")]

    operations = [
        migrations.AddField(
            model_name="clubrequest",
            name="is_deleted",
            field=models.BooleanField(db_index=True, default=False, verbose_name="Is deleted"),
        ),
        migrations.AddField(
            model_name="clubrequest",
            name="status",
            field=models.CharField(
                choices=[("waiting", "Waiting"), ("approved", "Approved"), ("declined", "Declined")],
                db_index=True,
                default="waiting",
                max_length=32,
                verbose_name="Status",
            ),
        ),
    ]
