# Generated by Django 2.1.5 on 2019-05-01 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("clubs", "0014_auto_20190428_1156")]

    operations = [
        migrations.AlterField(
            model_name="club",
            name="relationship_theme",
            field=models.CharField(
                choices=[("swing", "Swing"), ("bdsm", "Bdsm"), ("mixed", "Mixed")],
                db_index=True,
                max_length=16,
                verbose_name="Relationship themes",
            ),
        )
    ]
