# Generated by Django 2.1.5 on 2019-05-01 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("clubs", "0015_auto_20190501_0742")]

    operations = [
        migrations.AlterField(
            model_name="club",
            name="relationship_theme",
            field=models.CharField(
                choices=[("swing", "Swing"), ("bdsm", "Bdsm"), ("virt", "Virt"), ("other", "Other")],
                db_index=True,
                max_length=16,
                verbose_name="Relationship themes",
            ),
        )
    ]
