# Generated by Django 2.1.5 on 2019-05-01 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("clubs", "0016_auto_20190501_1814")]

    operations = [
        migrations.RemoveField(model_name="club", name="country"),
        migrations.RemoveField(model_name="club", name="region"),
    ]
