# Generated by Django 2.1.5 on 2019-05-04 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("clubs", "0017_auto_20190501_1939")]

    operations = []
