# Generated by Django 2.1.5 on 2019-05-04 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("clubs", "0019_club_geo_city_step1")]

    operations = []
