# Generated by Django 2.1.5 on 2019-05-04 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("clubs", "0020_auto_20190504_2228")]

    operations = []
