# Generated by Django 2.1.5 on 2019-05-05 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("clubs", "0023_remove_club_old_city")]

    operations = [
        migrations.AddField(
            model_name="club",
            name="status",
            field=models.CharField(
                choices=[("waiting", "Waiting"), ("approved", "Approved"), ("declined", "Declined")],
                db_index=True,
                default="waiting",
                max_length=32,
                verbose_name="Status",
            ),
        )
    ]
