# Generated by Django 2.1.5 on 2019-05-07 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("clubs", "0025_auto_20190507_0622")]

    operations = [
        migrations.AddField(
            model_name="club",
            name="is_ban",
            field=models.BooleanField(db_index=True, default=False, verbose_name="Is ban"),
        ),
        migrations.AddField(
            model_name="clubrequest",
            name="is_ban",
            field=models.BooleanField(db_index=True, default=False, verbose_name="Is ban"),
        ),
    ]
