# Generated by Django 2.1.5 on 2019-05-13 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("clubs", "0027_auto_20190507_0848")]

    operations = [
        migrations.AlterUniqueTogether(name="clubrequest", unique_together=set()),
        migrations.RemoveField(model_name="clubrequest", name="club"),
        migrations.RemoveField(model_name="clubrequest", name="user"),
        migrations.DeleteModel(name="ClubRequest"),
    ]
