# Generated by Django 2.1.5 on 2019-09-04 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("clubs", "0030_auto_20190516_2224")]

    operations = [migrations.RemoveField(model_name="club", name="city")]
