# Generated by Django 2.1.5 on 2019-09-04 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("cities_light", "0008_city_timezone"), ("clubs", "0031_auto_20190904_1218")]

    operations = [
        migrations.AddField(
            model_name="club",
            name="city",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="cities_light.City", verbose_name="City"
            ),
        ),
        migrations.AddField(
            model_name="club",
            name="city_old",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="geo.City", verbose_name="City"
            ),
        ),
    ]
