# Generated by Django 2.1.5 on 2019-09-09 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("clubs", "0033_auto_20190905_1117")]

    operations = [migrations.RemoveField(model_name="club", name="city_old")]
