# Generated by Django 2.1.5 on 2019-10-04 13:34

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("clubs", "0034_remove_club_city_old")]

    operations = [
        migrations.AddField(
            model_name="club",
            name="geo",
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name="Geo"),
        )
    ]
