# Generated by Django 2.1.5 on 2019-10-10 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("clubs", "0036_geo")]

    operations = [
        migrations.RemoveField(model_name="club", name="latitude"),
        migrations.RemoveField(model_name="club", name="longitude"),
    ]
