# Generated by Django 2.1.5 on 2020-02-16 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("clubs", "0037_auto_20191010_1625")]

    operations = [migrations.RenameField(model_name="club", old_name="avatar", new_name="image")]
