# Generated by Django 2.1.5 on 2020-02-16 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("clubs", "0041_auto_20200216_0817")]

    operations = [
        migrations.AlterField(
            model_name="club", name="address", field=models.TextField(null=True, verbose_name="Address")
        )
    ]
