# Generated by Django 2.1.5 on 2019-05-12 08:25

import uuid

import apps.memberships.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="MembershipRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_column="uuid", default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True, verbose_name="Created date")),
                ("updated_date", models.DateTimeField(auto_now=True, verbose_name="Updated date")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, verbose_name="Is deleted")),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[("waiting", "Waiting moderation"), ("approved", "Approved"), ("declined", "Declined")],
                        db_index=True,
                        max_length=32,
                        null=True,
                        verbose_name="Status",
                    ),
                ),
                ("is_ban", models.BooleanField(db_index=True, default=False, verbose_name="Is ban")),
                ("object_id", models.UUIDField(verbose_name="Object UUID")),
                (
                    "content_type",
                    models.ForeignKey(
                        limit_choices_to=apps.memberships.models.limit_choices_to_content_type,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.ContentType",
                        verbose_name="Content type",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="membership_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={"verbose_name": "Membership request", "verbose_name_plural": "Membership requests"},
        ),
        migrations.AlterUniqueTogether(
            name="membershiprequest", unique_together={("user", "content_type", "object_id")}
        ),
    ]
