# Generated by Django 2.1.5 on 2019-03-03 21:53

import uuid

import apps.comments.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [("contenttypes", "0002_remove_content_type_name")]

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_column="uuid", default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False, verbose_name="Is deleted")),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("object_id", models.UUIDField(verbose_name="Object UUID")),
                ("likes", models.PositiveIntegerField(default=0, verbose_name="Likes")),
                ("comment", models.TextField(verbose_name="Comment")),
                ("lft", models.PositiveIntegerField(db_index=True, editable=False)),
                ("rght", models.PositiveIntegerField(db_index=True, editable=False)),
                ("tree_id", models.PositiveIntegerField(db_index=True, editable=False)),
                ("level", models.PositiveIntegerField(db_index=True, editable=False)),
                (
                    "content_type",
                    models.ForeignKey(
                        limit_choices_to=apps.comments.models.limit_choices_to_content_type,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.ContentType",
                        verbose_name="Content type",
                    ),
                ),
            ],
            options={"verbose_name": "comment", "verbose_name_plural": "comments"},
        )
    ]
