# Generated by Django 2.1.5 on 2019-03-31 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("comments", "0003_auto_20190316_1304")]

    operations = [
        migrations.RemoveField(model_name="comment", name="is_deleted"),
        migrations.AddField(
            model_name="comment",
            name="status",
            field=models.CharField(
                choices=[("deleted", "Deleted"), ("created", "Created"), ("approved", "Approved")],
                default="created",
                max_length=32,
                verbose_name="Status",
            ),
        ),
    ]
