# Generated by Django 2.1.5 on 2019-04-13 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("comments", "0004_auto_20190331_2300")]

    operations = [
        migrations.AlterModelOptions(
            name="comment", options={"verbose_name": "Comment", "verbose_name_plural": "Comments"}
        )
    ]
