# Generated by Django 2.1.5 on 2019-04-14 18:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL), ("comments", "0005_auto_20190413_0524")]

    operations = [
        migrations.RemoveField(model_name="comment", name="likes"),
        migrations.AddField(
            model_name="comment",
            name="likes",
            field=models.ManyToManyField(
                blank=True, related_name="like_comments", to=settings.AUTH_USER_MODEL, verbose_name="Likes"
            ),
        ),
    ]
