# Generated by Django 2.1.5 on 2019-04-22 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("comments", "0007_auto_20190417_0627")]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={"ordering": ["created_date"], "verbose_name": "Comment", "verbose_name_plural": "Comments"},
        )
    ]
