# Generated by Django 3.0.5 on 2020-04-29 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("comments", "0008_auto_20190422_1616")]

    operations = [
        migrations.AlterField(model_name="comment", name="level", field=models.PositiveIntegerField(editable=False)),
        migrations.AlterField(model_name="comment", name="lft", field=models.PositiveIntegerField(editable=False)),
        migrations.AlterField(model_name="comment", name="rght", field=models.PositiveIntegerField(editable=False)),
    ]
