# Generated by Django 2.1.5 on 2019-04-13 14:18

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("users", "0003_auto_20190413_0524")]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="about",
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name="About"),
        )
    ]
