# Generated by Django 2.1.5 on 2019-04-17 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("users", "0006_auto_20190417_0627")]

    operations = [
        migrations.RemoveField(model_name="userfriend", name="created_date"),
        migrations.RemoveField(model_name="userfriend", name="is_deleted"),
        migrations.RemoveField(model_name="userfriend", name="updated_date"),
    ]
