# Generated by Django 2.1.5 on 2019-04-18 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("users", "0009_duplicates")]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("guest", "Guest"),
                    ("member", "Member"),
                    ("organizer", "Organizer"),
                    ("moderator", "Moderator"),
                ],
                default="guest",
                max_length=16,
                verbose_name="Role",
            ),
        )
    ]
