# Generated by Django 2.1.5 on 2019-04-24 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("users", "0010_auto_20190418_1104")]

    operations = [
        migrations.AddField(
            model_name="user",
            name="slug",
            field=models.SlugField(blank=True, max_length=150, null=True, unique=True, verbose_name="Slug"),
        )
    ]
