# Generated by Django 2.1.5 on 2019-04-27 20:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("users", "0013_auto_20190424_2036")]

    operations = [
        migrations.AlterField(
            model_name="userfriend",
            name="friend",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="friend_users",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Friend",
            ),
        )
    ]
