# Generated by Django 2.1.5 on 2019-04-28 08:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("users", "0015_set_slug")]

    operations = [
        migrations.AddField(
            model_name="user",
            name="friends",
            field=models.ManyToManyField(
                blank=True, related_name="_user_friends_+", to=settings.AUTH_USER_MODEL, verbose_name="Friends"
            ),
        )
    ]
