# Generated by Django 2.1.5 on 2019-04-28 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("users", "0018_set_friends")]

    operations = [
        migrations.AlterUniqueTogether(name="userfriend", unique_together=set()),
        migrations.RemoveField(model_name="userfriend", name="friend"),
        migrations.RemoveField(model_name="userfriend", name="user"),
        migrations.DeleteModel(name="UserFriend"),
    ]
