# Generated by Django 2.1.5 on 2019-05-01 18:14

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("users", "0019_auto_20190428_1047")]

    operations = [
        migrations.AlterModelOptions(
            name="friendrequest", options={"verbose_name": "Friend request", "verbose_name_plural": "Friend requests"}
        ),
        migrations.AlterField(
            model_name="user",
            name="relationship_formats",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("open_swing", "Open Swing"),
                        ("close_swing", "Close Swing"),
                        ("soft_swing", "Soft Swing"),
                        ("wmw", "WMW"),
                        ("mwm", "MWM"),
                        ("sexwife", "Sexwife"),
                        ("cuckold", "Cuckold"),
                        ("top", "Top"),
                        ("bottom", "Bottom"),
                        ("switch", "Switch"),
                    ],
                    max_length=16,
                ),
                null=True,
                size=None,
                verbose_name="Relationship formats",
            ),
        ),
    ]
