# Generated by Django 2.1.5 on 2019-05-01 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("users", "0020_auto_20190501_1814")]

    operations = [
        migrations.RemoveField(model_name="user", name="country"),
        migrations.RemoveField(model_name="user", name="region"),
    ]
