# Generated by Django 2.1.5 on 2019-05-04 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("users", "0021_auto_20190501_1939")]

    operations = []
