# Generated by Django 2.1.5 on 2019-05-04 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("users", "0023_user_geo_city_step1")]

    operations = []
