# Generated by Django 2.1.5 on 2019-05-07 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("users", "0027_friendrequest_is_ban")]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_ban",
            field=models.BooleanField(db_index=True, default=False, verbose_name="Is ban"),
        ),
        migrations.AddField(
            model_name="user",
            name="status",
            field=models.CharField(
                choices=[
                    ("waiting", "Waiting"),
                    ("waiting_moderation", "Waiting moderation"),
                    ("approved", "Approved"),
                    ("declined", "Declined"),
                ],
                db_index=True,
                default="waiting",
                max_length=32,
                verbose_name="Status",
            ),
        ),
    ]
