# Generated by Django 2.1.5 on 2019-05-13 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("users", "0030_users_moderation")]

    operations = [
        migrations.AlterUniqueTogether(name="friendrequest", unique_together=set()),
        migrations.RemoveField(model_name="friendrequest", name="friend"),
        migrations.RemoveField(model_name="friendrequest", name="user"),
        migrations.DeleteModel(name="FriendRequest"),
    ]
