# Generated by Django 2.1.5 on 2019-05-14 05:48

import uuid

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("users", "0031_auto_20190513_2139")]

    operations = [
        migrations.CreateModel(
            name="UserLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_column="uuid", default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True, verbose_name="Created date")),
                ("updated_date", models.DateTimeField(auto_now=True, verbose_name="Updated date")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, verbose_name="Is deleted")),
                ("link", models.CharField(max_length=255, verbose_name="Link")),
                ("description", models.TextField(blank=True, null=True, verbose_name="Description")),
                ("favicon", models.CharField(blank=True, max_length=255, null=True, verbose_name="Favicon")),
            ],
            options={"verbose_name": "User Link", "verbose_name_plural": "User Links"},
        ),
        migrations.AlterField(
            model_name="user",
            name="relationship_formats",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("open_swing", "Open Swing"),
                        ("close_swing", "Close Swing"),
                        ("soft_swing", "Soft Swing"),
                        ("wmw", "WMW"),
                        ("mwm", "MWM"),
                        ("sexwife", "Sexwife"),
                        ("hotwife", "Hotwife"),
                        ("cuckold", "Cuckold"),
                        ("cuckqueen", "Cuckqueen"),
                        ("top", "Top"),
                        ("bottom", "Bottom"),
                        ("switch", "Switch"),
                    ],
                    max_length=16,
                ),
                null=True,
                size=None,
                verbose_name="Relationship formats",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="relationship_themes",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("swing", "Swing"),
                        ("bdsm", "Bdsm"),
                        ("virt", "Virt"),
                        ("poliamoria", "Poliamoria"),
                        ("other", "Other"),
                    ],
                    max_length=16,
                ),
                null=True,
                size=None,
                verbose_name="Relationship themes",
            ),
        ),
        migrations.AddField(
            model_name="userlink",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name="User"
            ),
        ),
    ]
