# Generated by Django 2.1.5 on 2019-05-14 07:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("users", "0032_auto_20190514_0548")]

    operations = [
        migrations.CreateModel(
            name="UserOnline",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("last_seen", models.DateTimeField(verbose_name="Last seen")),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_online",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="userlink",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_userlinks",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
    ]
