# Generated by Django 2.1.5 on 2019-05-15 11:10

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("users", "0033_auto_20190514_0715")]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="relationship_formats",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("open_swing", "Open Swing"),
                        ("close_swing", "Close Swing"),
                        ("soft_swing", "Soft Swing"),
                        ("wmw", "WMW"),
                        ("mwm", "MWM"),
                        ("sexwife", "Sexwife"),
                        ("hotwife", "Hotwife"),
                        ("cuckold", "Cuckold"),
                        ("cuckqueen", "Cuckqueen"),
                        ("top", "Top"),
                        ("bottom", "Bottom"),
                        ("switch", "Switch"),
                        ("poliamoria", "Poliamoria"),
                        ("virt", "Virt"),
                        ("other", "Other"),
                    ],
                    max_length=16,
                ),
                null=True,
                size=None,
                verbose_name="Relationship formats",
            ),
        )
    ]
