# Generated by Django 2.1.5 on 2019-05-19 22:23

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("users", "0037_auto_20190516_2224")]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="gender",
            field=models.CharField(
                choices=[
                    ("m", "M"),
                    ("w", "W"),
                    ("family", "Family"),
                    ("mw", "MW"),
                    ("mm", "MM"),
                    ("ww", "WW"),
                    ("trans", "Trans"),
                ],
                max_length=255,
                null=True,
                verbose_name="Gender",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="relationship_formats",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("open_swing", "Open Swing"),
                        ("close_swing", "Close Swing"),
                        ("soft_swing", "Soft Swing"),
                        ("wmw", "WMW"),
                        ("mwm", "MWM"),
                        ("sexwife", "Sexwife"),
                        ("hotwife", "Hotwife"),
                        ("cuckold", "Cuckold"),
                        ("cuckqueen", "Cuckqueen"),
                        ("top", "Top"),
                        ("bottom", "Bottom"),
                        ("switch", "Switch"),
                        ("lgbt_active", "LGBT Active"),
                        ("lgbt_passive", "LGBT Passive"),
                        ("lgbt_switch", "LGBT Switch"),
                        ("format_poliamoria", "Poliamoria"),
                        ("format_virt", "Virt"),
                        ("format_other", "Other"),
                    ],
                    max_length=255,
                ),
                null=True,
                size=None,
                verbose_name="Relationship formats",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="relationship_status",
            field=models.CharField(
                choices=[("married", "Married"), ("dating", "Dating"), ("single", "Single")],
                max_length=255,
                null=True,
                verbose_name="Relationship status",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="relationship_themes",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("swing", "Swing"),
                        ("bdsm", "Bdsm"),
                        ("virt", "Virt"),
                        ("lgbt", "LGBT"),
                        ("poliamoria", "Poliamoria"),
                        ("other", "Other"),
                    ],
                    max_length=255,
                ),
                null=True,
                size=None,
                verbose_name="Relationship themes",
            ),
        ),
    ]
