# Generated by Django 2.1.5 on 2019-08-08 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("users", "0038_auto_20190519_2223")]

    operations = [migrations.RemoveField(model_name="user", name="relationship_status")]
