# Generated by Django 2.1.5 on 2019-08-14 06:49

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("users", "0039_remove_user_relationship_status")]

    operations = [
        migrations.CreateModel(
            name="BlackList",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_column="uuid", default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True, verbose_name="Created date")),
                ("updated_date", models.DateTimeField(auto_now=True, verbose_name="Updated date")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, verbose_name="Is deleted")),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("wanker", "Wanker"),
                            ("no_communication", "Don't wont to communicate with the user"),
                            ("just_so", "Just So"),
                            ("other", "Other"),
                        ],
                        max_length=255,
                        verbose_name="Reason",
                    ),
                ),
                ("reason_message", models.TextField(default="", verbose_name="Reason Message")),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="creator_blacklists",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_blacklists",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={"verbose_name": "User Link", "verbose_name_plural": "User Links"},
        ),
        migrations.AlterUniqueTogether(name="blacklist", unique_together={("creator", "user")}),
    ]
