# Generated by Django 2.1.5 on 2019-08-14 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("users", "0040_auto_20190814_0649")]

    operations = [
        migrations.AlterModelOptions(
            name="blacklist", options={"verbose_name": "Black List", "verbose_name_plural": "Black List"}
        )
    ]
