# Generated by Django 2.1.5 on 2019-08-14 10:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("users", "0041_auto_20190814_0850")]

    operations = [
        migrations.AddField(
            model_name="user",
            name="black_list",
            field=models.ManyToManyField(
                blank=True,
                related_name="user_black_list",
                through="users.BlackList",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Black List",
            ),
        )
    ]
