# Generated by Django 2.1.5 on 2019-08-17 12:01

import apps.users.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("users", "0044_sociallink")]

    operations = [
        migrations.RemoveField(model_name="user", name="birthday_m"),
        migrations.RemoveField(model_name="user", name="birthday_w"),
        migrations.AddField(
            model_name="user",
            name="birthday",
            field=models.IntegerField(null=True, verbose_name="Birthday (M, W in WW or trans)"),
        ),
        migrations.AddField(
            model_name="user",
            name="birthday_second",
            field=models.IntegerField(null=True, verbose_name="Birthday second (W, M in MM)"),
        ),
    ]
