# Generated by Django 2.1.5 on 2019-08-17 12:46

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("users", "0045_auto_20190817_1201")]

    operations = [
        migrations.RemoveField(model_name="sociallink", name="creator"),
        migrations.AddField(
            model_name="user",
            name="social_links",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.URLField(), null=True, size=None, verbose_name="Social links"
            ),
        ),
        migrations.DeleteModel(name="SocialLink"),
    ]
