# Generated by Django 2.1.5 on 2019-08-17 12:55

import apps.users.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("users", "0046_auto_20190817_1246")]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="age",
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name="Age"),
        ),
        migrations.AlterField(
            model_name="user",
            name="birthday",
            field=models.IntegerField(blank=True, null=True, verbose_name="Birthday (M, W in WW or trans)"),
        ),
        migrations.AlterField(
            model_name="user",
            name="birthday_second",
            field=models.IntegerField(blank=True, null=True, verbose_name="Birthday second (W, M in MM)"),
        ),
    ]
