# Generated by Django 2.1.5 on 2019-08-19 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("users", "0049_auto_20190819_2046")]

    operations = [
        migrations.RemoveField(model_name="user", name="fb_link"),
        migrations.RemoveField(model_name="user", name="ok_link"),
        migrations.RemoveField(model_name="user", name="vk_link"),
    ]
