# Generated by Django 2.1.5 on 2019-08-19 23:12

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("users", "0050_auto_20190819_2130")]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="social_links",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.URLField(), blank=True, null=True, size=None, verbose_name="Social links"
            ),
        )
    ]
