# Generated by Django 2.1.5 on 2019-09-04 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("users", "0052_birthday")]

    operations = [migrations.RemoveField(model_name="user", name="city")]
