# Generated by Django 2.1.5 on 2019-09-04 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("users", "0054_user_city")]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="city_old",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="geo.City", verbose_name="City"
            ),
        )
    ]
