# Generated by Django 2.1.5 on 2019-09-05 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("users", "0055_auto_20190904_1219")]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="city_old",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="geo.City", verbose_name="City"
            ),
        )
    ]
