# Generated by Django 2.1.5 on 2019-09-09 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("users", "0056_auto_20190905_1117")]

    operations = [migrations.RemoveField(model_name="user", name="city_old")]
