# Generated by Django 2.1.5 on 2019-09-22 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("users", "0057_remove_user_city_old")]

    operations = [migrations.RemoveField(model_name="user", name="age")]
