# Generated by Django 2.1.5 on 2019-11-30 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("users", "0058_remove_user_age")]

    operations = [
        migrations.AddField(
            model_name="user", name="privacy", field=models.BooleanField(default=False, verbose_name="Active")
        )
    ]
