# Generated by Django 2.1.5 on 2020-02-17 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("users", "0060_auto_20200217_0636")]

    operations = [migrations.RenameField(model_name="user", old_name="slug", new_name="username")]
