# Generated by Django 2.1.5 on 2020-02-17 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("users", "0061_auto_20200217_0638")]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_email_verified",
            field=models.BooleanField(default=False, verbose_name="Is email verified"),
        ),
        migrations.AddField(
            model_name="user",
            name="is_phone_verified",
            field=models.BooleanField(default=False, verbose_name="Is phone verified"),
        ),
        migrations.AlterField(
            model_name="user",
            name="birthday",
            field=models.IntegerField(null=True, verbose_name="Birthday (M, W in WW or trans)"),
        ),
    ]
