# Generated by Django 2.2.10 on 2020-02-20 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("users", "0064_set_slug")]

    operations = [migrations.RenameField(model_name="user", old_name="username", new_name="slug")]
