# Generated by Django 2.2.10 on 2020-02-20 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("users", "0065_auto_20200220_1416")]

    operations = [
        migrations.AlterField(
            model_name="user", name="slug", field=models.SlugField(max_length=150, unique=True, verbose_name="Slug")
        )
    ]
