# Generated by Django 2.1.5 on 2019-04-24 08:30

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL)]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_column="uuid", default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True, verbose_name="Created date")),
                ("updated_date", models.DateTimeField(auto_now=True, verbose_name="Updated date")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, verbose_name="Is deleted")),
                (
                    "task_type",
                    models.CharField(
                        choices=[
                            ("user_guest", "Moderate guest user"),
                            ("user_real", "Moderate user to get real"),
                            ("post", "Moderate post to show it on site"),
                            ("media", "Moderate media to show it on site"),
                        ],
                        db_index=True,
                        max_length=16,
                        verbose_name="Type",
                    ),
                ),
                (
                    "task_status",
                    models.CharField(
                        choices=[("open", "Open"), ("close", "Close")],
                        db_index=True,
                        max_length=16,
                        verbose_name="Status",
                    ),
                ),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "assigned_to",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Assigned to",
                    ),
                ),
            ],
            options={"verbose_name": "Task", "verbose_name_plural": "Tasks"},
        )
    ]
