# Generated by Django 2.1.5 on 2019-04-24 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("management", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="task",
            name="task_priority",
            field=models.CharField(
                choices=[("low", "Low"), ("normal", "Normal"), ("high", "High")],
                db_index=True,
                default="normal",
                max_length=16,
                verbose_name="Priority",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="task_type",
            field=models.CharField(
                choices=[
                    ("moderation_guest", "Moderation of guest"),
                    ("moderation_real", "Moderation of real status"),
                    ("moderation_post", "Moderation of post"),
                    ("moderation_media", "Moderation of media"),
                ],
                db_index=True,
                max_length=16,
                verbose_name="Type",
            ),
        ),
    ]
