# Generated by Django 2.1.5 on 2019-04-24 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("management", "0002_auto_20190424_1058")]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="task_status",
            field=models.CharField(
                choices=[("new", "New"), ("in_progress", "In progress"), ("close", "Done")],
                db_index=True,
                max_length=16,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="task_type",
            field=models.CharField(
                choices=[
                    ("moderation_guest", "Moderation of guest"),
                    ("moderation_real", "Moderation of real status"),
                    ("moderation_post", "Moderation of post"),
                    ("moderation_media", "Moderation of media"),
                    ("other", "Other"),
                ],
                db_index=True,
                max_length=16,
                verbose_name="Type",
            ),
        ),
    ]
