# Generated by Django 2.1.5 on 2019-04-24 13:44

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("management", "0003_auto_20190424_1230")]

    operations = [
        migrations.AddField(
            model_name="task",
            name="params",
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name="Params"),
        ),
        migrations.AlterField(
            model_name="task",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="task",
            name="task_status",
            field=models.CharField(
                choices=[("new", "New"), ("done", "Done")],
                db_index=True,
                default="new",
                max_length=16,
                verbose_name="Status",
            ),
        ),
    ]
