# Generated by Django 2.1.5 on 2019-04-25 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("management", "0006_auto_20190424_1412")]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="task_type",
            field=models.CharField(
                choices=[
                    ("moderation_guest", "Moderation of guest"),
                    ("moderation_real", "Moderation of real status"),
                    ("moderation_post", "Moderation of post"),
                    ("moderation_media", "Moderation of media"),
                    ("other", "Other"),
                ],
                db_index=True,
                default="other",
                max_length=16,
                verbose_name="Type",
            ),
        )
    ]
