# Generated by Django 2.1.5 on 2019-05-05 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("management", "0009_set_slug")]

    operations = [
        migrations.AddField(
            model_name="task", name="is_auto", field=models.BooleanField(default=False, verbose_name="Is Auto")
        )
    ]
