# Generated by Django 2.1.5 on 2019-05-05 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("management", "0010_task_is_auto")]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="task_type",
            field=models.CharField(
                choices=[
                    ("moderation_guest", "Moderation of guest"),
                    ("moderation_real", "Moderation of real status"),
                    ("moderation_post", "Moderation of post"),
                    ("moderation_media", "Moderation of media"),
                    ("moderation_club", "Moderation of club"),
                    ("other", "Other"),
                ],
                db_index=True,
                default="other",
                max_length=16,
                verbose_name="Type",
            ),
        )
    ]
