# Generated by Django 2.1.5 on 2019-05-07 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("management", "0011_auto_20190505_1844")]

    operations = [migrations.RemoveField(model_name="task", name="assigned_to"), migrations.DeleteModel(name="Task")]
