# Generated by Django 2.1.5 on 2019-04-09 21:46

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Log",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_column="uuid", default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("deleted", "Deleted"), ("created", "Created"), ("approved", "Approved")],
                        default="created",
                        max_length=32,
                        verbose_name="Status",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True, verbose_name="Created date")),
                ("updated_date", models.DateTimeField(auto_now=True, verbose_name="Updated date")),
                ("logger_name", models.CharField(max_length=100, verbose_name="Logger name")),
                (
                    "level",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "NotSet"),
                            (20, "Info"),
                            (30, "Warning"),
                            (10, "Debug"),
                            (40, "Error"),
                            (50, "Fatal"),
                        ],
                        db_index=True,
                        default=40,
                        verbose_name="Level",
                    ),
                ),
                ("msg", models.TextField(verbose_name="Msg")),
                ("trace", models.TextField(blank=True, null=True, verbose_name="Trace")),
            ],
            options={"verbose_name": "Log", "verbose_name_plural": "Logs", "ordering": ("-created_date",)},
        )
    ]
