# Generated by Django 2.1.5 on 2019-04-12 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("logs", "0001_initial")]

    operations = [
        migrations.AlterModelOptions(
            name="log", options={"ordering": ("-created_date",), "verbose_name": "log", "verbose_name_plural": "logs"}
        )
    ]
