# Generated by Django 2.1.5 on 2019-04-13 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("logs", "0002_auto_20190412_2158")]

    operations = [
        migrations.AlterModelOptions(
            name="log", options={"ordering": ("-created_date",), "verbose_name": "Log", "verbose_name_plural": "Logs"}
        )
    ]
