# Generated by Django 2.1.5 on 2019-04-13 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("media", "0004_auto_20190412_2213")]

    operations = [
        migrations.AlterModelOptions(name="media", options={"verbose_name": "Media", "verbose_name_plural": "Media"})
    ]
