# Generated by Django 2.1.5 on 2019-04-13 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("media", "0005_auto_20190413_0524")]

    operations = [
        migrations.AddField(
            model_name="media",
            name="is_hot_dating",
            field=models.BooleanField(default=False, verbose_name="Is hot dating"),
        )
    ]
