# Generated by Django 2.1.5 on 2019-04-13 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("media", "0006_media_is_hot_dating")]

    operations = [
        migrations.RemoveField(model_name="media", name="is_hot_dating"),
        migrations.AddField(
            model_name="media",
            name="sub_status",
            field=models.CharField(
                blank=True, choices=[("hot_dating", "Hot dating")], max_length=32, null=True, verbose_name="Sub Status"
            ),
        ),
    ]
