# Generated by Django 2.1.5 on 2019-04-17 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("media", "0008_auto_20190414_1804")]

    operations = [
        migrations.RemoveField(model_name="media", name="status"),
        migrations.AddField(
            model_name="media",
            name="is_deleted",
            field=models.BooleanField(db_index=True, default=False, verbose_name="Is deleted"),
        ),
    ]
