# Generated by Django 2.1.5 on 2019-04-17 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("media", "0009_auto_20190417_0627")]

    operations = [
        migrations.AddField(
            model_name="media",
            name="status",
            field=models.CharField(
                choices=[("waiting", "Waiting"), ("approved", "Approved"), ("declined", "Declined")],
                db_index=True,
                default="waiting",
                max_length=32,
                verbose_name="Status",
            ),
        )
    ]
