# Generated by Django 2.1.5 on 2019-04-17 09:51

import uuid

import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("storage", "0003_auto_20190417_0627"),
        ("media", "0010_media_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="HotDaiting",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_column="uuid", default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True, verbose_name="Created date")),
                ("updated_date", models.DateTimeField(auto_now=True, verbose_name="Updated date")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, verbose_name="Is deleted")),
                (
                    "status",
                    models.CharField(
                        choices=[("waiting", "Waiting"), ("approved", "Approved"), ("declined", "Declined")],
                        db_index=True,
                        default="waiting",
                        max_length=32,
                        verbose_name="Status",
                    ),
                ),
                ("description", ckeditor.fields.RichTextField(blank=True, null=True, verbose_name="Description")),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name="Creator"
                    ),
                ),
                (
                    "image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="storage.Image", verbose_name="Image"
                    ),
                ),
            ],
            options={"verbose_name": "Hot Dating", "verbose_name_plural": "Hot Dating"},
        )
    ]
