# Generated by Django 2.1.5 on 2019-05-05 13:42

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL), ("media", "0011_hotdaiting")]

    operations = [
        migrations.CreateModel(
            name="MediaFolder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_column="uuid", default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True, verbose_name="Created date")),
                ("updated_date", models.DateTimeField(auto_now=True, verbose_name="Updated date")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, verbose_name="Is deleted")),
                (
                    "status",
                    models.CharField(
                        choices=[("waiting", "Waiting"), ("approved", "Approved"), ("declined", "Declined")],
                        db_index=True,
                        default="waiting",
                        max_length=32,
                        verbose_name="Status",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Media Tag")),
                (
                    "show_media",
                    models.CharField(
                        choices=[
                            ("no_users", "No users"),
                            ("only_friends", "Only friends"),
                            ("all_users", "All users"),
                        ],
                        default="only_friends",
                        max_length=16,
                        verbose_name="Show media",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name="Creator"
                    ),
                ),
            ],
            options={"verbose_name": "Media Folder", "verbose_name_plural": "Media Folder"},
        ),
        migrations.RemoveField(model_name="media", name="sub_status"),
    ]
