# Generated by Django 2.1.5 on 2019-05-05 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("media", "0013_media_folders")]

    operations = [migrations.RemoveField(model_name="mediafolder", name="status")]
