# Generated by Django 2.1.5 on 2019-05-07 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("media", "0015_auto_20190507_0622")]

    operations = [
        migrations.AddField(
            model_name="hotdaiting",
            name="is_ban",
            field=models.BooleanField(db_index=True, default=False, verbose_name="Is ban"),
        ),
        migrations.AddField(
            model_name="media",
            name="is_ban",
            field=models.BooleanField(db_index=True, default=False, verbose_name="Is ban"),
        ),
    ]
