# Generated by Django 2.1.5 on 2019-05-07 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("media", "0016_auto_20190507_0700")]

    operations = [
        migrations.AlterField(
            model_name="hotdaiting",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[("waiting", "Waiting moderation"), ("approved", "Approved"), ("declined", "Declined")],
                db_index=True,
                max_length=32,
                null=True,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="media",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[("waiting", "Waiting moderation"), ("approved", "Approved"), ("declined", "Declined")],
                db_index=True,
                max_length=32,
                null=True,
                verbose_name="Status",
            ),
        ),
    ]
