# Generated by Django 2.1.5 on 2019-05-17 20:23

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("media", "0018_media_moderation")]

    operations = [
        migrations.RemoveField(model_name="media", name="hash_tags"),
        migrations.AddField(
            model_name="media",
            name="hashtags",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=255), default=list, size=None, verbose_name="Hash tags"
            ),
        ),
    ]
