# Generated by Django 2.1.5 on 2019-09-23 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("media", "0021_auto_20190807_1349")]

    operations = [
        migrations.AlterField(
            model_name="media",
            name="video_code",
            field=models.TextField(blank=True, null=True, verbose_name="Embed video code"),
        )
    ]
