# Generated by Django 2.1.5 on 2020-02-16 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("media", "0022_auto_20190923_1917")]

    operations = [migrations.RemoveField(model_name="media", name="hot_daiting_status")]
