# Generated by Django 2.1.5 on 2019-03-31 23:00

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="File",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_column="uuid", default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("deleted", "Deleted"), ("created", "Created"), ("approved", "Approved")],
                        default="created",
                        max_length=32,
                        verbose_name="Status",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True, verbose_name="Created date")),
                ("updated_date", models.DateTimeField(auto_now=True, verbose_name="Updated date")),
                ("name", models.CharField(blank=True, max_length=255, null=True, verbose_name="Name")),
                ("file", models.FileField(upload_to="", verbose_name="File")),
            ],
            options={"verbose_name": "File", "verbose_name_plural": "Files"},
        ),
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_column="uuid", default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("deleted", "Deleted"), ("created", "Created"), ("approved", "Approved")],
                        default="created",
                        max_length=32,
                        verbose_name="Status",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True, verbose_name="Created date")),
                ("updated_date", models.DateTimeField(auto_now=True, verbose_name="Updated date")),
                ("name", models.CharField(blank=True, max_length=255, null=True, verbose_name="Name")),
                ("image", models.ImageField(upload_to="", verbose_name="Image")),
            ],
            options={"verbose_name": "Image", "verbose_name_plural": "Images"},
        ),
    ]
