# Generated by Django 2.1.5 on 2019-04-17 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("storage", "0002_auto_20190331_2300")]

    operations = [
        migrations.RemoveField(model_name="file", name="status"),
        migrations.RemoveField(model_name="image", name="status"),
        migrations.AddField(
            model_name="file",
            name="is_deleted",
            field=models.BooleanField(db_index=True, default=False, verbose_name="Is deleted"),
        ),
        migrations.AddField(
            model_name="image",
            name="is_deleted",
            field=models.BooleanField(db_index=True, default=False, verbose_name="Is deleted"),
        ),
    ]
