# Generated by Django 2.1.5 on 2019-09-23 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("storage", "0003_auto_20190417_0627")]

    operations = [
        migrations.AddField(
            model_name="image",
            name="isFromEditor",
            field=models.BooleanField(default=False, verbose_name="Is from editor"),
        )
    ]
