# Generated by Django 2.1.5 on 2019-04-12 22:13

import apps.posts.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("posts", "0003_remove_post_published_for_all")]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="content_type",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to=apps.posts.models.limit_choices_to_content_type,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.ContentType",
                verbose_name="Content type",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="object_id",
            field=models.UUIDField(blank=True, null=True, verbose_name="Object UUID"),
        ),
    ]
