# Generated by Django 2.1.5 on 2019-04-24 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("posts", "0008_post_status")]

    operations = [
        migrations.AddField(
            model_name="post",
            name="slug",
            field=models.SlugField(blank=True, max_length=150, null=True, unique=True, verbose_name="Slug"),
        )
    ]
