# Generated by Django 2.1.5 on 2019-04-24 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("posts", "0010_set_slug")]

    operations = [
        migrations.AlterField(
            model_name="post", name="slug", field=models.SlugField(max_length=150, unique=True, verbose_name="Slug")
        )
    ]
