# Generated by Django 2.1.5 on 2019-05-17 20:23

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("posts", "0015_posts_moderation")]

    operations = [
        migrations.RemoveField(model_name="post", name="hash_tags"),
        migrations.AddField(
            model_name="post",
            name="hashtags",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=255), default=list, size=None, verbose_name="Hash tags"
            ),
        ),
    ]
