# Generated by Django 2.1.5 on 2019-12-17 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("posts", "0017_auto_20190517_2023")]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="theme",
            field=models.CharField(
                blank=True,
                choices=[
                    ("swing", "Swing"),
                    ("swing_history", "Swing History"),
                    ("bdsm", "Bdsm"),
                    ("bdsm_history", "Bdsm History"),
                    ("lgbt", "Lgbt"),
                    ("lgbt_history", "Lgbt History"),
                    ("sex", "Sex"),
                    ("sex_history", "Sex History"),
                    ("rule", "Rule"),
                    ("rule_media", "Rule Media"),
                    ("advertisment", "Advertisment"),
                ],
                max_length=64,
                null=True,
                verbose_name="Theme",
            ),
        )
    ]
