# Generated by Django 2.1.5 on 2020-01-21 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("posts", "0018_auto_20191217_1023")]

    operations = [
        migrations.AddField(
            model_name="post", name="is_whisper", field=models.BooleanField(default=False, verbose_name="Is Whisper")
        )
    ]
