# Generated by Django 2.1.5 on 2019-05-24 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("geo", "0002_auto_20190523_2140")]

    operations = [
        migrations.AddField(
            model_name="city",
            name="is_important",
            field=models.BooleanField(default=False, verbose_name="Is_important"),
        )
    ]
