# Generated by Django 2.1.5 on 2019-09-09 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("users", "0057_remove_user_city_old"), ("geo", "0003_city_is_important")]

    operations = [
        migrations.RemoveField(model_name="city", name="country"),
        migrations.RemoveField(model_name="city", name="region"),
        migrations.RemoveField(model_name="region", name="country"),
        migrations.DeleteModel(name="City"),
        migrations.DeleteModel(name="Country"),
        migrations.DeleteModel(name="Region"),
    ]
