# Generated by Django 2.1.5 on 2019-03-31 23:00

import apps.chat.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def chat_limit_choices_to_content_type():
    return ()


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("storage", "0002_auto_20190331_2300"),
        ("chat", "0001_initial"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="creator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name="Creator"
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="viewed_by",
            field=models.ManyToManyField(
                blank=True, related_name="user_viewed_chats", to=settings.AUTH_USER_MODEL, verbose_name="Viewed by"
            ),
        ),
        migrations.AddField(
            model_name="chat",
            name="administrator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name="Administrator"
            ),
        ),
        migrations.AddField(
            model_name="chat",
            name="avatar",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="storage.Image",
                verbose_name="Avatar",
            ),
        ),
        migrations.AddField(
            model_name="chat",
            name="content_type",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to=chat_limit_choices_to_content_type,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.ContentType",
                verbose_name="Content type",
            ),
        ),
        migrations.AddField(
            model_name="chat",
            name="moderators",
            field=models.ManyToManyField(
                blank=True, related_name="moderator_chats", to=settings.AUTH_USER_MODEL, verbose_name="Moderators"
            ),
        ),
        migrations.AddField(
            model_name="chat",
            name="users",
            field=models.ManyToManyField(
                blank=True, related_name="user_chats", to=settings.AUTH_USER_MODEL, verbose_name="Users"
            ),
        ),
    ]
