# Generated by Django 2.1.5 on 2019-04-12 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("chat", "0002_auto_20190331_2300")]

    operations = [migrations.RenameField(model_name="chat", old_name="administrator", new_name="creator")]
