# Generated by Django 2.1.5 on 2019-04-12 22:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("chat", "0003_auto_20190412_2209")]

    operations = [
        migrations.AlterField(
            model_name="chat",
            name="creator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name="Creator"
            ),
        )
    ]
