# Generated by Django 2.1.5 on 2019-04-14 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("chat", "0006_auto_20190413_0524")]

    operations = [
        migrations.AlterModelOptions(
            name="message",
            options={
                "ordering": ["chat__created_date", "created_date"],
                "verbose_name": "Message",
                "verbose_name_plural": "Messages",
            },
        )
    ]
