# Generated by Django 2.1.5 on 2019-04-14 21:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("chat", "0008_auto_20190414_1925")]

    operations = [
        migrations.RemoveField(model_name="chatban", name="created_date"),
        migrations.RemoveField(model_name="chatban", name="status"),
        migrations.RemoveField(model_name="chatban", name="updated_date"),
        migrations.AddField(
            model_name="chatban",
            name="ban_date",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name="Ban date"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="chatban",
            name="minutes",
            field=models.PositiveIntegerField(default=5, verbose_name="Ban minutes"),
        ),
    ]
