# Generated by Django 2.1.5 on 2019-04-15 18:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0002_auto_20190331_2300"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("chat", "0009_auto_20190414_2131"),
    ]

    operations = [
        migrations.AddField(
            model_name="chat",
            name="bans",
            field=models.ManyToManyField(
                blank=True,
                related_name="user_chat_bans",
                through="chat.ChatBan",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Users",
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="attachments",
            field=models.ManyToManyField(
                blank=True, related_name="attachmnets_chats", to="storage.Image", verbose_name="Attachments"
            ),
        ),
    ]
