# Generated by Django 2.1.5 on 2019-04-15 19:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("chat", "0010_auto_20190415_1859")]

    operations = [
        migrations.AlterField(
            model_name="chat",
            name="name",
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="chat",
            name="object_id",
            field=models.UUIDField(blank=True, db_index=True, null=True, verbose_name="Object UUID"),
        ),
        migrations.AlterField(
            model_name="chatban",
            name="chat",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chat_chatbans",
                to="chat.Chat",
                verbose_name="Chat",
            ),
        ),
        migrations.AlterField(
            model_name="chatban",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_chatbans",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="chat",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chat_messages",
                to="chat.Chat",
                verbose_name="Chat",
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="creator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="creator_messages",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creator",
            ),
        ),
    ]
