# Generated by Django 2.1.5 on 2019-04-17 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("chat", "0012_auto_20190416_1744")]

    operations = [
        migrations.RemoveField(model_name="chat", name="status"),
        migrations.RemoveField(model_name="conversation", name="status"),
        migrations.RemoveField(model_name="message", name="status"),
        migrations.AddField(
            model_name="chat",
            name="is_deleted",
            field=models.BooleanField(db_index=True, default=False, verbose_name="Is deleted"),
        ),
        migrations.AddField(
            model_name="conversation",
            name="is_deleted",
            field=models.BooleanField(db_index=True, default=False, verbose_name="Is deleted"),
        ),
        migrations.AddField(
            model_name="message",
            name="is_deleted",
            field=models.BooleanField(db_index=True, default=False, verbose_name="Is deleted"),
        ),
        migrations.AlterField(
            model_name="message",
            name="chat",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chat_messages",
                to="chat.Chat",
                verbose_name="Chat",
            ),
        ),
    ]
