# Generated by Django 2.1.5 on 2019-04-17 06:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("chat", "0013_auto_20190417_0627")]

    operations = [
        migrations.AddField(
            model_name="chatban",
            name="created_date",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now, verbose_name="Created date"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="chatban",
            name="updated_date",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated date"),
        ),
    ]
