# Generated by Django 2.1.5 on 2019-04-17 06:43

import django.utils.timezone
from django.db import migrations, models


def migration(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    Message = apps.get_model("chat", "Message")
    Chat = apps.get_model("chat", "Chat")
    ContentType = apps.get_model("contenttypes", "ContentType")
    db_alias = schema_editor.connection.alias
    for message in Message.objects.using(db_alias).filter(chat__isnull=False):
        message.object_id = message.chat_id
        message.content_type = ContentType.objects.get_for_model(Chat)
        message.save(update_fields=("object_id", "content_type"))
    Message.objects.using(db_alias).filter(content_type__isnull=True).delete()


class Migration(migrations.Migration):

    dependencies = [("chat", "0014_auto_20190417_0643")]

    operations = [migrations.RunPython(migration)]
