# Generated by Django 2.1.5 on 2019-04-17 06:43

import django.utils.timezone
from django.db import migrations, models


def migration(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    Message = apps.get_model("chat", "Message")
    Message.objects.using(db_alias).filter(content_type__isnull=True).delete()


class Migration(migrations.Migration):

    dependencies = [("chat", "0015_messages")]

    operations = [migrations.RunPython(migration)]
