# Generated by Django 2.1.5 on 2019-04-17 06:43

import django.utils.timezone
from django.db import migrations, models


def migration(apps, schema_editor):
    Message = apps.get_model("chat", "Message")
    db_alias = schema_editor.connection.alias
    for message in Message.objects.using(db_alias).all():
        message.chat_id = message.object_id
        message.save(update_fields=("chat_id",))


class Migration(migrations.Migration):

    dependencies = [("chat", "0018_auto_20190417_1925")]

    operations = [migrations.RunPython(migration)]
