# Generated by Django 2.1.5 on 2019-04-17 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("chat", "0019_messages")]

    operations = [
        migrations.RemoveField(model_name="message", name="content_type"),
        migrations.RemoveField(model_name="message", name="object_id"),
        migrations.AlterField(
            model_name="message",
            name="chat",
            field=models.ForeignKey(
                default=None, on_delete=django.db.models.deletion.CASCADE, to="chat.Chat", verbose_name="Chat"
            ),
            preserve_default=False,
        ),
    ]
