# Generated by Django 2.1.5 on 2019-04-18 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("chat", "0020_auto_20190417_1928")]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="chat",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chat_messages",
                to="chat.Chat",
                verbose_name="Chat",
            ),
        )
    ]
