# Generated by Django 2.1.5 on 2019-04-22 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("chat", "0021_auto_20190418_1044")]

    operations = [
        migrations.AddField(
            model_name="chat",
            name="chat_type",
            field=models.CharField(
                choices=[
                    ("chat", "Chat"),
                    ("conversation", "Conversation"),
                    ("chat_with_moderators", "Chat with moderators"),
                ],
                default="chat",
                max_length=64,
                verbose_name="Chat type",
            ),
        )
    ]
