# Generated by Django 2.1.5 on 2019-04-27 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("chat", "0024_messages")]

    operations = [
        migrations.AlterField(
            model_name="chat",
            name="chat_type",
            field=models.CharField(
                choices=[
                    ("chat", "Chat"),
                    ("conversation", "Conversation"),
                    ("chat_with_moderators", "Chat with moderators"),
                    ("chat_with_developers", "Chat with developers"),
                ],
                db_index=True,
                default="chat",
                max_length=64,
                verbose_name="Chat type",
            ),
        )
    ]
