# Generated by Django 2.1.5 on 2019-09-23 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("chat", "0025_auto_20190427_0549")]

    operations = [
        migrations.AlterField(
            model_name="message", name="message", field=models.TextField(blank=True, null=True, verbose_name="Message")
        )
    ]
