# Generated by Django 2.2.10 on 2020-03-12 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("chat", "0027_auto_20200216_0714")]

    operations = [
        migrations.AlterField(
            model_name="chat",
            name="chat_type",
            field=models.CharField(
                choices=[
                    ("chat", "Chat"),
                    ("conversation", "Conversation"),
                    ("chat_with_moderators", "Chat with moderators"),
                ],
                db_index=True,
                default="chat",
                max_length=64,
                verbose_name="Chat type",
            ),
        )
    ]
